---

cdap_loadbalancer_vip: "{{ site_floating_ip.ip }}"
cluster_name: '{{ site_inventory_name }}-reflex-platform'
site_deployment_type: "{{{site_deployment_type}}"
install_using_public_repos: "false"
cdap_master_nodes: "master-nodes"
cdap_management_nodes: "management-nodes"
raf_docker_registry: "artifacts.ggn.in.guavus.com:4245"
ambari_admin_user: 'admin'
ambari_admin_password: 'Sbe7UGkRBMF8'
cdap_properties_dir: "/opt/guavus/ambari-api/cdap/properties"
site_default_rpm_repo_host: "artifacts.ggn.in.guavus.com:80"
cdap_version: '5.1.204'
cdap_major_version: '5.1.204'
spark2_2_home: "/usr/hdp/{{ hdp_version }}-{{ hdp_build }}/spark2"
install_guavus_accelerator: true

#----------------------------------------
#         kerberos Config
# Below information is required for cdap 
# keytab and principal generation.
#----------------------------------------
krb_admin_principal: "changeit"
krb_admin_password: "changeit"

#-------------------------
# Enable Security For CDAP
#-------------------------

is_authentication_enabled: true
is_authorization_enabled: true

#-----------------------------------------
# Enable Guavus Analytics Engine Services
#-----------------------------------------

cdap__ui_theme_name: 'afe'
cdap__ui_theme_file: 'ui/server/config/themes/{{cdap__ui_theme_name}}.json'
cdap__data_tx_max_timeout: 3600
cdap__data_tx_timeout: 3600

