---

cdap_properties_dir: "/opt/guavus/ambari-api/cdap/properties"
postgres_port: 5432
mysql_port: 3306
rangeradmin_username: "admin"
rangeradmin_password: "Sbe7UGkRBMF8"

cdap_user_policy_config: |
  {
   "name":"cdap_user",
   "service": "{{ cdap_cluster_name }}_yarn",
   "isEnabled": true,
   "isAuditEnabled": true,
   "resources": {
        "queue": {
            "values": [
                "default"
            ],
            "isExcludes": false,
            "isRecursive": true
        }
    },
    "policyItems": [
        {
            "accesses": [
                {
                    "type": "submit-app",
                    "isAllowed": true
                },
                {
                    "type": "admin-queue",
                    "isAllowed": true
                }
            ],
            "users": [
                "cdap",
                "hbase"
            ],
            "groups": [],
            "conditions": [],
            "delegateAdmin": false
        }
    ],
    "denyPolicyItems": [],
    "allowExceptions": [],
    "denyExceptions": [],
    "dataMaskPolicyItems": [],
    "rowFilterPolicyItems": []
  }
cdap_path_policy_config: |
  {
   "name":"cdap_path",
   "service": "{{ cdap_cluster_name }}_hadoop",
   "isEnabled": true,
   "isAuditEnabled": true,
   "resources": {
        "path": {
            "values": [
                "/user/cdap",
                "/cdap/tx.snapshot",
                "/apps/hive/",
                "/cdap/"
            ],
            "isExcludes": false,
            "isRecursive": true
        }
    },
    "policyItems": [
        {
            "accesses": [
                {
                    "type": "write",
                    "isAllowed": true
                },
                {
                    "type": "read",
                    "isAllowed": true
                },
                {
                    "type": "execute",
                    "isAllowed": true
                }
            ],
            "users": [
                "cdap"
            ],
            "groups": [],
            "conditions": [],
            "delegateAdmin": false
        }
    ],
    "denyPolicyItems": [],
    "allowExceptions": [],
    "denyExceptions": [],
    "dataMaskPolicyItems": [],
    "rowFilterPolicyItems": []
  }
yarn_path_policy_config: |
  {
   "name":"cdap_yarn_path",
   "service": "{{ cdap_cluster_name }}_hadoop",
   "isEnabled": true,
   "isAuditEnabled": true,
   "resources": {
        "path": {
            "values": [
                "/cdap"
            ],
            "isExcludes": false,
            "isRecursive": true
        }
    },
    "policyItems": [
        {
            "accesses": [
                {
                    "type": "write",
                    "isAllowed": true
                },
                {
                    "type": "read",
                    "isAllowed": true
                },
                {
                    "type": "execute",
                    "isAllowed": true
                }
            ],
            "users": [
                "yarn"
            ],
            "groups": [],
            "conditions": [],
            "delegateAdmin": false
        }
    ],
    "denyPolicyItems": [],
    "allowExceptions": [],
    "denyExceptions": [],
    "dataMaskPolicyItems": [],
    "rowFilterPolicyItems": []
  }
hbase_all_policy_config: |
  {
   "name":"hbase-cdap-all",
   "service": "{{ cdap_cluster_name }}_hbase",
   "isEnabled": true,
   "isAuditEnabled": true,
        "resources": {
            "column-family": {
                "values": [
                    "*"
                ],
                "isExcludes": false,
                "isRecursive": false
            },
            "column": {
                "values": [
                    "*"
                ],
                "isExcludes": false,
                "isRecursive": false
            },
            "table": {
                "values": [
                    "cdap*.*",
                    "*"
                ],
                "isExcludes": false,
                "isRecursive": false
            }
        },
        "policyItems": [
            {
                "accesses": [
                    {
                        "type": "read",
                        "isAllowed": true
                    },
                    {
                        "type": "write",
                        "isAllowed": true
                    },
                    {
                        "type": "create",
                        "isAllowed": true
                    },
                    {
                        "type": "admin",
                        "isAllowed": true
                    }
                ],
                "users": [
                    "cdap",
                ],
                "groups": [],
                "conditions": [],
                "delegateAdmin": false
            }
        ],
        "denyPolicyItems": [],
        "allowExceptions": [],
        "denyExceptions": [],
        "dataMaskPolicyItems": [],
        "rowFilterPolicyItems": []
  }
